/*
 * ProfileManagerFrame.java
 *
 * Created on 17. únor 2008, 13:32
 */
package cz.srubarovi.teacher;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  Stepan
 */
public class ProfileManagerFrame extends javax.swing.JFrame {

    /** Creates new form ProfileManagerFrame */
    public ProfileManagerFrame() {
        initComponents();
        //listProfiles(); //neni inicializovano, blby napad
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListProfiles = new javax.swing.JList();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldCurrentProfile = new javax.swing.JTextField();
        jLabelCurrentProfile = new javax.swing.JLabel();

        jListProfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProfilesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProfiles);

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldCurrentProfile.setEditable(false);

        jLabelCurrentProfile.setText("Current profile:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCurrentProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCurrentProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentProfile)
                    .addComponent(jTextFieldCurrentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String newProfile=JOptionPane.showInputDialog(this, "Enter new profile name.", "default");
        ProfileManager.createProfile(newProfile);
        Settings.INSTANCE.setStatsProfile(newProfile);
        listProfiles();
}//GEN-LAST:event_jButtonAddActionPerformed

    private void jListProfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProfilesMouseClicked
        update();
        
    }//GEN-LAST:event_jListProfilesMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileManagerFrame().setVisible(true);
            }
        });
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if(b) {
            listProfiles();
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabelCurrentProfile;
    private javax.swing.JList jListProfiles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCurrentProfile;
    // End of variables declaration//GEN-END:variables

    private void listProfiles() {
        DefaultListModel model=new DefaultListModel();
        if(ProfileManager.listProfiles()!=null) {
            for (String s : ProfileManager.listProfiles()) {
                model.addElement(s);
            }
        }
        jListProfiles.setModel(model); 
        
        jTextFieldCurrentProfile.setText(Settings.INSTANCE.getStatsProfile());
    }

    private void update() {
        String profile=jListProfiles.getSelectedValue().toString();
        Settings.INSTANCE.setStatsProfile(profile);
        listProfiles();
    }
    
}
