/*
 * SettingsDialog.java
 *
 * Created on 17. zברם 2007, 17:49
 */

package cz.srubarovi.teacher;

import cz.srubarovi.teacher.questioner.Questioner;
import java.awt.Font;
import javax.swing.SpinnerNumberModel;

import static cz.srubarovi.teacher.Settings.i18nText;

/**
 *
 * @author  Stepan
 */
public class SettingsDialog extends javax.swing.JDialog {
    
    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        
        for (Questioner q : Settings.INSTANCE.getQuestioners())
            questionersBox.addItem(q);
        
        questionersBox.setSelectedItem(Settings.INSTANCE.getDefaultQuestioner());
        
        jCheckBoxTimer.setSelected(Settings.INSTANCE.isTimerEnabled());
        if(Settings.INSTANCE.isTimerEnabled())
            jSpinnerTimer.setValue(Settings.INSTANCE.getTimer());
        jSpinnerTimerBonus.setValue(Settings.INSTANCE.getTimerBonusPerLetter());
     
        //init RTL box
        jCheckBoxRTLQuestion.setSelected(Settings.INSTANCE.isRTLQuestion());
        jCheckBoxRTLAnswer.setSelected(Settings.INSTANCE.isRTLAnswer());
        
        setFontButtonText();
    }
    
    private void setFontButtonText() {
        Font font=Settings.INSTANCE.getFont();
        
        //format changefont button
        String strStyle=" [family=" + font.getFamily() + ",name=" + font.getName() + ",style=";
        if (font.isBold()) {
            strStyle += font.isItalic() ? "bolditalic" : "bold";
        } else {
            strStyle += font.isItalic() ? "italic" : "plain";
        }
        
        strStyle += ",size=" + font.getSize() + "]";
        
        jButtonFont.setText(i18nText("settingsdialog_changefontbutton")+strStyle);
        pack();        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        questionersBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanelTimer = new javax.swing.JPanel();
        jCheckBoxTimer = new javax.swing.JCheckBox();
        jSpinnerTimer = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerTimerBonus = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButtonFont = new javax.swing.JButton();
        jPanelRTL = new javax.swing.JPanel();
        jCheckBoxRTLQuestion = new javax.swing.JCheckBox();
        jCheckBoxRTLAnswer = new javax.swing.JCheckBox();

        setTitle("Settings");
        questionersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionersBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Default language suggest:");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelTimer.setBorder(javax.swing.BorderFactory.createTitledBorder("Timer"));
        jCheckBoxTimer.setText("Max");
        jCheckBoxTimer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxTimer.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jSpinnerTimer.setModel(new SpinnerNumberModel(2000, 0, Integer.MAX_VALUE, 100));

        jLabel2.setText("ms for a word");

        jLabel3.setText("+");

        jSpinnerTimerBonus.setModel(new SpinnerNumberModel(200, 0, Integer.MAX_VALUE, 10));

        jLabel4.setText("ms per letter");

        javax.swing.GroupLayout jPanelTimerLayout = new javax.swing.GroupLayout(jPanelTimer);
        jPanelTimer.setLayout(jPanelTimerLayout);
        jPanelTimerLayout.setHorizontalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTimerBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanelTimerLayout.createSequentialGroup()
                        .addComponent(jCheckBoxTimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelTimerLayout.setVerticalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimerLayout.createSequentialGroup()
                .addGroup(jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTimer)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerTimerBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFontActionPerformed(evt);
            }
        });

        jPanelRTL.setBorder(javax.swing.BorderFactory.createTitledBorder("Right-to-left"));
        jCheckBoxRTLQuestion.setText("Question");
        jCheckBoxRTLQuestion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxRTLQuestion.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxRTLAnswer.setText("Answer and help");
        jCheckBoxRTLAnswer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxRTLAnswer.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanelRTLLayout = new javax.swing.GroupLayout(jPanelRTL);
        jPanelRTL.setLayout(jPanelRTLLayout);
        jPanelRTLLayout.setHorizontalGroup(
            jPanelRTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRTLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxRTLQuestion)
                    .addComponent(jCheckBoxRTLAnswer))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanelRTLLayout.setVerticalGroup(
            jPanelRTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRTLLayout.createSequentialGroup()
                .addComponent(jCheckBoxRTLQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxRTLAnswer)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionersBox, 0, 144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOK))
                    .addComponent(jPanelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFont, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(questionersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFontActionPerformed
        FontChooser fc=new FontChooser(this, "", Settings.INSTANCE.getFont());
        fc.setVisible(true);
        if(fc.getNewFont()!=null) {
            Settings.INSTANCE.setFont(fc.getNewFont());
            setFontButtonText();
        }
    }//GEN-LAST:event_jButtonFontActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        //questioner
        Settings.INSTANCE.setDefaultQuestioner((Questioner) questionersBox.getSelectedItem());
        
        //timer
        if(jCheckBoxTimer.isSelected()) {
            Settings.INSTANCE.setTimer((Integer) jSpinnerTimer.getValue());
            Settings.INSTANCE.setTimerBonusPerLetter((Integer) jSpinnerTimerBonus.getValue());
        } else
            Settings.INSTANCE.setTimer(Settings.INSTANCE.TIMER_DISABLED);
        
        //RTL
        Settings.INSTANCE.setRTLQuestion(jCheckBoxRTLQuestion.isSelected());
        Settings.INSTANCE.setRTLAnswer(jCheckBoxRTLAnswer.isSelected());
        
        setVisible(false);
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    private void questionersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionersBoxActionPerformed
        
    }//GEN-LAST:event_questionersBoxActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFont;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxRTLAnswer;
    private javax.swing.JCheckBox jCheckBoxRTLQuestion;
    private javax.swing.JCheckBox jCheckBoxTimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelRTL;
    private javax.swing.JPanel jPanelTimer;
    private javax.swing.JSpinner jSpinnerTimer;
    private javax.swing.JSpinner jSpinnerTimerBonus;
    private javax.swing.JComboBox questionersBox;
    // End of variables declaration//GEN-END:variables
    
}
