/*
 * TestSelectionFrame.java
 *
 * Created on 25. duben 2006, 13:44
 */

package cz.srubarovi.teacher;

import cz.srubarovi.teacher.core.DataTest;
import cz.srubarovi.teacher.core.LangDefManager;
import cz.srubarovi.teacher.core.SmartTest;
import cz.srubarovi.teacher.core.StatsTest;
import cz.srubarovi.teacher.core.Test;
import cz.srubarovi.teacher.core.TestJoin;
import cz.srubarovi.teacher.core.TestReverse;
import cz.srubarovi.teacher.core.TestShuffle;
import cz.srubarovi.teacher.nodes.CheckNode;
import cz.srubarovi.teacher.nodes.NodeEntry;
import cz.srubarovi.teacher.resources.Resources;
import cz.srubarovi.teacher.strategy.AbstractStrategy;
import cz.srubarovi.teacher.strategy.Strategy;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.zip.ZipEntry;
import java.util.zip.ZipException;
import java.util.zip.ZipFile;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTree;

/**
 *
 * @author  Imjagpul
 */
public class TestSelectionFrame extends javax.swing.JFrame {
    
    private ProfileManagerFrame profileManagerFrame=new ProfileManagerFrame();
    
    /** Creates new form TestSelectionFrame */
    public TestSelectionFrame() {
        initComponents();
        LangDefManager.INSTANCE.addDir(getStartFolder());
        jCheckBoxWordTypes.setVisible(LangDefManager.INSTANCE.showWordTypes());
        updateEnabledState();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CheckNode root=createRootNode();
        jTreeTestSelection = new JTree(root);
        jCheckBoxReverse = new javax.swing.JCheckBox();
        jCheckBoxAccents = new javax.swing.JCheckBox();
        jCheckBoxWordTypes = new javax.swing.JCheckBox();
        jTabbedPaneSettings = new javax.swing.JTabbedPane();
        jPanelSimpleMode = new javax.swing.JPanel();
        jCheckBoxSmart = new javax.swing.JCheckBox();
        jCheckBoxShuffle = new javax.swing.JCheckBox();
        jPanelStatsMode = new javax.swing.JPanel();
        jComboBoxStrategy = new javax.swing.JComboBox();
        jCheckBoxCollectStats = new javax.swing.JCheckBox();
        jMenuBarMainMenu = new javax.swing.JMenuBar();
        jMenuEditor = new javax.swing.JMenu();
        jMenuItemRunEditor = new javax.swing.JMenuItem();
        jMenuStats = new javax.swing.JMenu();
        jMenuItemSelectProfile = new javax.swing.JMenuItem();
        jMenuItemBrowseStats = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Resources.APP);

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jTreeTestSelection.setToggleClickCount(0);
        CheckNode.initTree(jTreeTestSelection);
        jScrollPane1.setViewportView(jTreeTestSelection);

        jCheckBoxReverse.setText("Reverse");
        jCheckBoxReverse.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxReverse.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jCheckBoxReverse.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxAccents.setText("Accents");
        jCheckBoxAccents.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxAccents.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBoxAccents.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxWordTypes.setText("WordTypes");
        jCheckBoxWordTypes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxWordTypes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBoxWordTypes.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxSmart.setSelected(true);
        jCheckBoxSmart.setText("Smart");
        jCheckBoxSmart.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxSmart.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jCheckBoxSmart.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxShuffle.setSelected(true);
        jCheckBoxShuffle.setText("Shuffle");
        jCheckBoxShuffle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxShuffle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jCheckBoxShuffle.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanelSimpleModeLayout = new javax.swing.GroupLayout(jPanelSimpleMode);
        jPanelSimpleMode.setLayout(jPanelSimpleModeLayout);
        jPanelSimpleModeLayout.setHorizontalGroup(
            jPanelSimpleModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimpleModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSimpleModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSmart)
                    .addComponent(jCheckBoxShuffle))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanelSimpleModeLayout.setVerticalGroup(
            jPanelSimpleModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimpleModeLayout.createSequentialGroup()
                .addComponent(jCheckBoxSmart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPaneSettings.addTab("Simple mode", jPanelSimpleMode);

        jComboBoxStrategy.setModel(new DefaultComboBoxModel(AbstractStrategy.getStrategyList()));

        jCheckBoxCollectStats.setText("Collect statistics");
        jCheckBoxCollectStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxCollectStats.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBoxCollectStats.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxCollectStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCollectStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStatsModeLayout = new javax.swing.GroupLayout(jPanelStatsMode);
        jPanelStatsMode.setLayout(jPanelStatsModeLayout);
        jPanelStatsModeLayout.setHorizontalGroup(
            jPanelStatsModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatsModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatsModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCollectStats, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxStrategy, 0, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelStatsModeLayout.setVerticalGroup(
            jPanelStatsModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatsModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxCollectStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jComboBoxStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneSettings.addTab("Statistics mode", jPanelStatsMode);

        jMenuEditor.setMnemonic('e');
        jMenuEditor.setText("Editor");

        jMenuItemRunEditor.setMnemonic('e');
        jMenuItemRunEditor.setText("Run editor");
        jMenuItemRunEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditorActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemRunEditor);

        jMenuBarMainMenu.add(jMenuEditor);

        jMenuStats.setText("Stats");

        jMenuItemSelectProfile.setText("Select profile");
        jMenuItemSelectProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectProfileActionPerformed(evt);
            }
        });
        jMenuStats.add(jMenuItemSelectProfile);

        jMenuItemBrowseStats.setText("Browse stats");
        jMenuItemBrowseStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBrowseStatsActionPerformed(evt);
            }
        });
        jMenuStats.add(jMenuItemBrowseStats);

        jMenuBarMainMenu.add(jMenuStats);

        setJMenuBar(jMenuBarMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxReverse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRun)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxWordTypes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxAccents))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAccents)
                    .addComponent(jCheckBoxWordTypes))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxReverse)
                    .addComponent(jButtonRun))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateEnabledState() {
        boolean collectStats=jCheckBoxCollectStats.isSelected();
        jComboBoxStrategy.setEnabled(collectStats);        
        jCheckBoxShuffle.setEnabled(!collectStats);
        jCheckBoxSmart.setEnabled(!collectStats);
    }
    
    private void makeSureLoggedIn() {
        initStatsDir();
        
        if(Settings.INSTANCE.getStatsProfile()!=null)
            return;
        
        int count=ProfileManager.getProfileCount();
        if(count==0) {
            String newProfile=JOptionPane.showInputDialog(this, "Enter new profile name.", "default");
            Settings.INSTANCE.setStatsProfile(newProfile);
        } else if(count==1) {
            Settings.INSTANCE.setStatsProfile(ProfileManager.listProfiles()[0]);
        } else {
            Settings.INSTANCE.setStatsProfile(ProfileManager.listProfiles()[0]);
            profileManagerFrame.setVisible(true);
        }        
    }
    
    private void jCheckBoxCollectStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCollectStatsActionPerformed
        makeSureLoggedIn();
        updateEnabledState();
    }//GEN-LAST:event_jCheckBoxCollectStatsActionPerformed
    
    TestEditorFrame editor=null;
    private void jMenuEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditorActionPerformed
        if(editor==null) {
            editor=new TestEditorFrame();
        }
        editor.setVisible(true);
    }//GEN-LAST:event_jMenuEditorActionPerformed
    
    QuestionFrame frame;
    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        Test test=null;
        
        CheckNode root=(CheckNode) jTreeTestSelection.getModel().getRoot();
        ArrayList<DataTest> selectedTest=new ArrayList<DataTest>();
        ArrayList<String> pathnames=new ArrayList<String>();
        
        for (Enumeration en=root.preorderEnumeration(); en.hasMoreElements();) {
            CheckNode node = (CheckNode) en.nextElement();
            if(node.isLeaf() && node.isSelected()) {
                NodeEntry entry=(NodeEntry) node.getUserObject();
                try {
                    selectedTest.add(entry.getType().loadTest(entry));
                    pathnames.add(entry.getPathname());
                } catch (TestFileFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Unkown file format:"+entry.toString());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "IO exception:"+entry.toString());
                }
            }
        }
        
        if(selectedTest.size()==0) {
            JOptionPane.showMessageDialog(this, "První zaškrtni testy, které chceš spustit.");
            return;
        }
        
        if(!jCheckBoxCollectStats.isSelected()) {
            
            test=new TestJoin(selectedTest);
            
            if(jCheckBoxShuffle.isSelected()) test=new TestShuffle(test);
            if(jCheckBoxReverse.isSelected()) test=new TestReverse(test);
            if(jCheckBoxSmart.isSelected()) test=new SmartTest(test);
        } else {
            
            assert selectedTest.size()>0; //uz to bylo testovano
            assert pathnames.size()==selectedTest.size();
            
            DataTest[] dataTestArray=new DataTest[selectedTest.size()];
            String[] pathnamesArray=new String[dataTestArray.length];
            
            dataTestArray=selectedTest.toArray(dataTestArray);
            pathnamesArray=pathnames.toArray(pathnamesArray);
            
            Strategy strategy=(Strategy) jComboBoxStrategy.getSelectedItem();            
            test=StatsTest.load(dataTestArray, pathnamesArray, jCheckBoxReverse.isSelected(), strategy);
        }
        
        
        if(frame==null) {
            frame=new QuestionFrame();
        }
        
        frame.setTestAccents(jCheckBoxAccents.isSelected());
        frame.setTestWordTypes(jCheckBoxWordTypes.isSelected());
        frame.startTest(test);
    }//GEN-LAST:event_jButtonRunActionPerformed

    private StatsBrowser statsBrowser;
    private void jMenuItemBrowseStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBrowseStatsActionPerformed
        makeSureLoggedIn();
        
        if (statsBrowser == null) {
            statsBrowser = new StatsBrowser();
        }

        CheckNode root = (CheckNode) jTreeTestSelection.getModel().getRoot();
        ArrayList<String> pathnames = new ArrayList<String>();

        for (Enumeration en = root.preorderEnumeration(); en.hasMoreElements();) {
            CheckNode node = (CheckNode) en.nextElement();
            if (node.isLeaf() && node.isSelected()) {
                NodeEntry entry = (NodeEntry) node.getUserObject();
                pathnames.add(entry.getPathname());
            }
        }

        if(pathnames.size()==0) {
            JOptionPane.showMessageDialog(this, "První zaškrtni testy, jejihž statistiku chceš prozkoumat.");
            return;
        }
        
        statsBrowser.setPathnames(pathnames);
        statsBrowser.setVisible(true);

    }//GEN-LAST:event_jMenuItemBrowseStatsActionPerformed

    private void jMenuItemSelectProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectProfileActionPerformed
        initStatsDir();
        profileManagerFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemSelectProfileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TestSelectionFrame().setVisible(true);
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestSelectionFrame().setVisible(true);
            }
        });
         **/
    }
    
    private CheckNode parseJar(final File srcFile) {
        //open as zip file
        ZipFile testFile;
        try {
            testFile = new ZipFile(srcFile);
        } catch (ZipException ex) {
            ex.printStackTrace();
            return null;
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        }
        
        //create root (archive) node
        CheckNode root=new CheckNode(new NodeEntry() {
            public InputStream getInputStream() {
                return null;
            }
            @Override
            public String toString() {
                String name=srcFile.getName();
                return name.substring(0, name.lastIndexOf("."));
            }
            
            public Icon getIcon() {
                return Resources.ARCHIVE;
            }
            
            public String getPathname() {
                return ProfileManager.getTestPathname(srcFile);
            }
            
            public NodeEntry.TestType getType() {
                return null;
            }
        }, true, false);
        
        //create one node for each file in archive
        for (Enumeration<? extends ZipEntry> en = testFile.entries(); en.hasMoreElements();) {
            ZipEntry zentry = en.nextElement();
            if(zentry.isDirectory()) continue;
            
            final String zEntryName=zentry.getName();
            NodeEntry entry=new NodeEntry() {
                public InputStream getInputStream() {
                    try {
                        ZipFile zfile=new ZipFile(srcFile);
                        return zfile.getInputStream(zfile.getEntry(zEntryName));
                    } catch (ZipException ex) {
                        ex.printStackTrace();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                    return null;
                }
                
                @Override
                public String toString() {
                    return zEntryName;
                }
                
                public Icon getIcon() {
                    return null;
                }
                
                public NodeEntry.TestType getType() {
                    return srcFile.getName().endsWith(".xml") ? NodeEntry.TestType.XML : NodeEntry.TestType.TESTv1;
                    //TODO : bug asi
                }
                
                public String getPathname() {
                    return ProfileManager.getTestPathname(srcFile)+zEntryName;
                }
            };
            
            root.add(new CheckNode(entry, false, false));
        }
        
        return root;
    }
    
    private CheckNode parseTestDic(File dic) {
        assert dic.isDirectory();
        CheckNode root=new CheckNode(dic.getName(), true, false);
        
        for (final File file : dic.listFiles()) {
            if (file.isHidden()) continue; //Ignore hidden files
            if (file.getName().startsWith(".")) continue; //Ignore hidden files
            
            if(file.isDirectory()) {
                root.add(parseTestDic(file));
            } else if(file.getName().endsWith(".jar")) {
                root.add(parseJar(file));
            } else {
                NodeEntry entry=new NodeEntry() {
                    public InputStream getInputStream() {
                        try {
                            return new FileInputStream(file);
                        } catch (FileNotFoundException ex) {
                            ex.printStackTrace();
                        }
                        return null;
                    }
                    @Override
                    public String toString() {
                        return file.getName();
                    }
                    
                    public Icon getIcon() {
                        return null;
                    }
                    
                    public NodeEntry.TestType getType() {
                        return file.getName().endsWith(".xml") ? NodeEntry.TestType.XML : NodeEntry.TestType.TESTv1;
                    }
                    
                    public String getPathname() {
                        return ProfileManager.getTestPathname(file);
                    }
                };
                
                root.add(new CheckNode(entry, false, false));
            }
        }
        return root;
    }
    
    private File getStartFolder() {
        File dictDir=Settings.INSTANCE.getDictDir();
        
        if(dictDir==null) {
            File startFolder=new File("../slovniky");
            if(!startFolder.exists()) startFolder=new File("slovniky");
            if(!startFolder.exists()) {
                boolean result=startFolder.mkdir();
                if(result)
                    JOptionPane.showMessageDialog(this, "Adresáø slovníky nebyl nalezen; byl vytvoøen.", "Adresáø slovníky nenalezen", JOptionPane.INFORMATION_MESSAGE);
                else {
                    JOptionPane.showMessageDialog(this, "Adresáø slovníky nebyl nalezen, ani se ho nepodaøilo vytvoøit.", "Adresáø slovníky nenalezen", JOptionPane.ERROR_MESSAGE);
                    return null;
                }
            }
            
            dictDir=startFolder;
            Settings.INSTANCE.setDictDir(dictDir);
        }
        
        return dictDir;
    }
    
    private void initStatsDir() {
        if(Settings.INSTANCE.getStatsDir()==null) {
            File statsDir=new File(getStartFolder().getParent(), "stats");
            if(!statsDir.exists()) {
                boolean result=statsDir.mkdir();
                if(result)
                    JOptionPane.showMessageDialog(this, "Adresáø pro statistky nebyl nalezen; byl vytvoøen.", "Adresáø slovníky nenalezen", JOptionPane.INFORMATION_MESSAGE);
                else {
                    JOptionPane.showMessageDialog(this, "Adresáø pro statistky nebyl nalezen, ani se ho nepodaøilo vytvoøit.", "Adresáø slovníky nenalezen", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            if(statsDir.exists())
                Settings.INSTANCE.setStatsDir(statsDir);
        }
    }
    
    private CheckNode createRootNode() {
        return parseTestDic(getStartFolder());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRun;
    private javax.swing.JCheckBox jCheckBoxAccents;
    private javax.swing.JCheckBox jCheckBoxCollectStats;
    private javax.swing.JCheckBox jCheckBoxReverse;
    private javax.swing.JCheckBox jCheckBoxShuffle;
    private javax.swing.JCheckBox jCheckBoxSmart;
    private javax.swing.JCheckBox jCheckBoxWordTypes;
    private javax.swing.JComboBox jComboBoxStrategy;
    private javax.swing.JMenuBar jMenuBarMainMenu;
    private javax.swing.JMenu jMenuEditor;
    private javax.swing.JMenuItem jMenuItemBrowseStats;
    private javax.swing.JMenuItem jMenuItemRunEditor;
    private javax.swing.JMenuItem jMenuItemSelectProfile;
    private javax.swing.JMenu jMenuStats;
    private javax.swing.JPanel jPanelSimpleMode;
    private javax.swing.JPanel jPanelStatsMode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneSettings;
    private javax.swing.JTree jTreeTestSelection;
    // End of variables declaration//GEN-END:variables
    
}
