//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.21 at 07:58:55 odp. CEST 
//


package cz.srubarovi.teacher.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for language element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="language">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;all>
 *           &lt;element name="wordTypes" type="{http://srubarovi.cz/teacher}wordTypes" minOccurs="0"/>
 *           &lt;element name="accentDefinition" type="{http://srubarovi.cz/teacher}accentDefiniton" minOccurs="0"/>
 *         &lt;/all>
 *         &lt;attribute name="langcode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "language")
public class Language {

    @XmlElement(namespace = "http://srubarovi.cz/teacher")
    protected WordTypes wordTypes;
    @XmlElement(namespace = "http://srubarovi.cz/teacher")
    protected AccentDefiniton accentDefinition;
    @XmlAttribute
    protected String langcode;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the wordTypes property.
     * 
     * @return
     *     possible object is
     *     {@link WordTypes }
     *     
     */
    public WordTypes getWordTypes() {
        return wordTypes;
    }

    /**
     * Sets the value of the wordTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordTypes }
     *     
     */
    public void setWordTypes(WordTypes value) {
        this.wordTypes = value;
    }

    /**
     * Gets the value of the accentDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link AccentDefiniton }
     *     
     */
    public AccentDefiniton getAccentDefinition() {
        return accentDefinition;
    }

    /**
     * Sets the value of the accentDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccentDefiniton }
     *     
     */
    public void setAccentDefinition(AccentDefiniton value) {
        this.accentDefinition = value;
    }

    /**
     * Gets the value of the langcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangcode() {
        return langcode;
    }

    /**
     * Sets the value of the langcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangcode(String value) {
        this.langcode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
