//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.21 at 07:58:55 odp. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://srubarovi.cz/teacher")
package cz.srubarovi.teacher.xml;
